### ISSUE TITLE
Bulk uploding reply email generating

### ISSUE THREAD

**Issue by PasanMethsaraMOE** [moe-lk/bulk-upload#1]

**Comment by PasanMethsaraMOE** [comment]
When teacher/principal uploading a excel sheet, the reply mail should be sent to the relevant teacher, principal, zonal coordinator.
The subject of the mail should be "Rejection of Bulk Uploading CENCUS_NO-GRADE/CLASS".

**Comment by mohamednizar** [comment]
done
