### ISSUE TITLE
Bulk Upload Testing

### ISSUE THREAD

**Issue by mohamednizar** [moe-lk/bulk-upload#45]
- [x]  Email delay issue - fixed
- [x] On insert and update skip the errors and insert rest , also send an error message with partial success report.
- [x] Complained on ID number and Admission number validation. - Fixed
- [x] Many more improvements with performance issues as well.
- [x ] Send emails for unverified email address

**Comment by resha007** [comment]
(Complained on ID number and Admission number validation. - Fixed)
for 1st row, no issue in the number.
from the 2nd row, the error remains.

**Comment by resha007** [comment]
(Email delay issue - fixed)
this is ok

**Comment by resha007** [comment]
when the all the rows successfully uploaded, the reply email said that partial success.

**Comment by resha007** [comment]
(Complained on ID number and Admission number validation. - Fixed)
this is ok

**Comment by resha007** [comment]
(Send emails for unverified email address)
this is ok

**Comment by resha007** [comment]
(On insert and update skip the errors and insert rest , also send an error message with partial success report.)
this is ok
